# Generated by Django 2.2.4 on 2021-06-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAuth',
        ),
    ]
