# Generated by Django 3.2.4 on 2021-06-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
